# Generated by Django 5.2.6 on 2025-09-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tmdb', models.PositiveIntegerField(unique=True)),
                ('payload', models.JSONField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-atualizado_em',),
            },
        ),
        migrations.AlterField(
            model_name='critica',
            name='nota',
            field=models.IntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], default=5),
        ),
    ]
