# Generated by Django 5.2.6 on 2025-09-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0002_filmecache_alter_critica_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
