# Generated by Django 5.2.6 on 2025-09-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_lista_itemlista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critica',
            name='usuario',
        ),
    ]
