name: CI/CD Backstage - Azure

on:
  push:
    branches: [ prod ]  # de main para prod
  pull_request:
    branches: [ prod ]  # de main para prod

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  AZURE_WEBAPP_NAME: 'backstage-app'  # ⚠️ Trocar pelo nome real do Azure

jobs:
  # JOB 1: TESTES UNITÁRIOS
  test:
    name: Executar Testes Unitários Django
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache de dependências Python
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    
    - name: Instalar dependências Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Executar testes unitários Django
      run: |
        python manage.py test
      env:
        TARGET_ENV: 'development'
        TMDB_API_KEY: 'e2bf84876d17e898ef5fc63655cd5040'
    
    - name: Verificar migrações pendentes
      run: |
        python manage.py makemigrations --check --dry-run
      env:
        TARGET_ENV: 'development'

  # JOB 2: TESTES E2E CYPRESS
  test-e2e:
    name: Executar Testes E2E (Cypress)
    needs: test  # Só roda se testes unitários passarem
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Cache de dependências Python
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    
    - name: Cache de dependências Node
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
    - name: Instalar dependências Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Instalar dependências Node
      run: |
        npm ci
    
    - name: Aplicar migrações
      run: |
        python manage.py migrate
      env:
        TARGET_ENV: 'development'
    
    - name: Iniciar servidor Django em background
      run: |
        python manage.py runserver 8000 > django.log 2>&1 &
        echo "Aguardando servidor iniciar..."
        sleep 10
      env:
        TARGET_ENV: 'development'
        TMDB_API_KEY: 'e2bf84876d17e898ef5fc63655cd5040'
    
    - name: Verificar se servidor está rodando
      run: |
        curl -f http://localhost:8000 || (cat django.log && exit 1)
    
    - name: Executar testes Cypress
      uses: cypress-io/github-action@v6
      with:
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 120
        browser: chrome
        record: false
        config-file: cypress.config.js
    
    - name: Upload screenshots em caso de falha
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        retention-days: 7
    
    - name: Upload vídeos dos testes
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos
        retention-days: 7
    
    - name: Exibir logs do Django em caso de falha
      if: failure()
      run: |
        echo "===== LOGS DO DJANGO ====="
        cat django.log

  # JOB 3: BUILD
  build:
    name: Build do Projeto
    needs: [test, test-e2e]  # Só roda se ambos os testes passarem
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache de dependências Python
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Coletar arquivos estáticos
      run: |
        python manage.py collectstatic --noinput
      env:
        TARGET_ENV: 'development'
        DJANGO_STATIC_URL: '/static/'
    
    - name: Verificar build
      run: |
        echo "📦 Build concluído com sucesso"
        ls -la staticfiles/

  # JOB 4: DEPLOY AZURE
  deploy:
    name: Deploy para Azure
    needs: [test, test-e2e, build]  # Só roda se tudo passar
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'  # ✅ Mudado para prod
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Criar ambiente virtual e instalar dependências
      run: |
        python -m venv antenv
        source antenv/bin/activate
        pip install -r requirements.txt
    
    - name: Coletar arquivos estáticos para produção
      run: |
        source antenv/bin/activate
        python manage.py collectstatic --noinput
      env:
        TARGET_ENV: 'production'
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    
    - name: Comprimir arquivos para deploy
      run: |
        zip -r deploy.zip . -x "*.git*" "*.github*" "*__pycache__*" "*.pyc" "db.sqlite3" "node_modules/*" "cypress/*"
    
    - name: Deploy para Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip
    
    - name: Notificar sucesso
      if: success()
      run: |
        echo "✅ Deploy realizado com sucesso!"
        echo "🎬 Backstage está no ar no Azure!"
        echo "🌐 URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
    
    - name: Notificar falha
      if: failure()
      run: |
        echo "❌ Deploy falhou. Verifique os logs no Azure Portal."
        echo "📋 Acesse: https://portal.azure.com"